# docker-compose.yml
version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      # DATABASE_URL: mysql://app_user:app_password@mysql:3306/currency_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENEXCHANGERATES_APP_ID: your-openexchangerates-app-id
      # JWT_ACCESS_SECRET: change-me-access-secret-min-32-chars-here
      # JWT_REFRESH_SECRET: change-me-refresh-secret-min-32-chars-here
    depends_on:
      # mysql:
      #   condition: service_healthy
      redis:
        condition: service_healthy

  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: currency_db
  #     MYSQL_USER: app_user
  #     MYSQL_PASSWORD: app_password
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

# volumes:
#   mysql_data:
